speaker_sx="speaker_img_spr"
speaker_ix=0
itext=""
itext_col=c_black
itext_a=1
itext_cut_til=1
itext_length=0
itext_max_length= string_length(itext)
talk_box_col=c_white
talk_box_a=1
speaker_place=1
speaker_number=4
speaker_box_col= c_white
speaker_box_a= 1
s_n_col=c_black
s_n_a=1
speaker_box1_on= true
speaker_box2_on= false
speaker_box3_on= false
speaker_box4_on= false
letter_limit= 15
story1= ""
